repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
            - id: check-added-large-files
              args: ['--maxkb=700']
            - id: check-json
            - id: end-of-file-fixer
            - id: requirements-txt-fixer
            - id: trailing-whitespace
            - id: check-yaml
              args:
                  - --allow-multiple-documents
            - id: pretty-format-json
              args:
                  - --autofix
              exclude: ^tests/.*
    -   repo: https://github.com/psf/black
        rev: 21.11b1
        hooks:
            - id: black
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 4.0.1
        hooks:
            - id: flake8
